var request = require("request");
var Discord = require("discord.js");

exports.commands = [
    "inspirobot"
]

exports.inspirobot = {
	description: "returns an inspirational image generated by inspirobot",
	process: function(bot,msg,suffix){
		request({
			url: "http://inspirobot.me/api?generate=true"
		},
		function(err,res,body){
            if(body.length > 0){
                msg.channel.send("", {
                    embed: {
                        "image": {
                            url: body
                        }
                    }
                });
            } else {
                msg.channel.send("No inspiration to be had :(");
            }
		});
	}
}
